name: backend

on:
  push:
    branches: 
      - main
    paths:
      - 'server/**'
  pull_request:
    branches: ["*"]
    paths:
      - 'server/**'

jobs:
  Testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node: 18
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./server
      
      - name: Lint
        run: npm run back:lint
      
      - name: Testing
        run: npm run back:test